package fr.insaif.jajagaa.view;

import java.util.List;

/**
 * La classe représente la Vue du plan et est composée de tous les tronçons, les noeuds et les tournées du modèle.
 * @author alicia
 */
public class VuePlan extends javax.swing.JPanel implements VueElement {

    private List<VueNoeud> noeuds;
    private List<VueTroncon> troncons;
    private List<VueTournee> tournees;
    
    
    /**
     * Constructeur de la classe VuePlan
     */
    public VuePlan(List<VueNoeud> desNoeuds, List<VueTroncon> desTroncons, List<VueTournee> desTournees) {
        noeuds = desNoeuds;
        troncons = desTroncons;
        tournees = desTournees;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
