package fr.insaif.jajagaa.view;

import fr.insaif.jajagaa.model.Troncon;

/**
 * Classe qui implémente la vue d'un tronçon.
 * @author alicia
 */
public class VueTroncon extends javax.swing.JPanel implements VueElement {

    /**
     * Troncon à partir duquel la VueTroncon est implémentée.
     */
    private Troncon tronconModel;
    /**
     * Coordonnée X du noeud d'origine du tronçon.
     */
    private int origViewX;
    /**
     * Coordonnée Y du noeud d'origine du tronçon.
     */
    private int origViewY;
    /**
     * Coordonnée X du noeud de destination du tronçon.
     */
    private int destViewX;
    /**
     * Coordonnée Y du noeud de destination du tronçon.
     */
    private int destViewY;
    /**
     * Coefficient de conversion entre les coordonnées du modèle et la vue. 
     */
    private int conv;
    /**
     * Vitesse à laquelle on peut rouler sur le tronconModel.
     */
    private float vitesse;
    
    
    /**
     * Constructeur de la classe VueTroncon.
     * @param unTroncon 
     */
    public VueTroncon(Troncon unTroncon) {
        tronconModel = unTroncon;
        origViewX = unTroncon.getOrigine().getX()*conv;
        origViewY = unTroncon.getOrigine().getY()*conv;
        destViewX = unTroncon.getDestination().getX()*conv;
        destViewY = unTroncon.getDestination().getY()*conv;
        vitesse = unTroncon.getVitesse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
